Fix rust error in parse.rs
```
error: getter function appears to return the wrong field
   --> automerge/src/storage/parse.rs:311:5
    |
311 | /     pub(crate) fn bytes(&self) -> &'a [u8] {
312 | |         self.original
    | |         ------------- help: consider using: `self.bytes`
313 | |     }
    | |_____^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#misnamed_getters
    = note: `-D clippy::misnamed-getters` implied by `-D warnings`

error: could not compile `automerge` due to previous error
```

Revert "Fix rust error in parse.rs"

This reverts commit e3b7317698d2cc3de709044eb5557e124b8bddac.

Ignore misnamed_getters clippy error

```
error: getter function appears to return the wrong field
--> automerge/src/storage/parse.rs:311:5
|
311 | / pub(crate) fn bytes(&self) -> &'a [u8] {
312 | | self.original
| | ------------- help: consider using: `self.bytes`
313 | | }
| |_____^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#misnamed_getters
= note: `-D clippy::misnamed-getters` implied by `-D warnings`

error: could not compile `automerge` due to previous error
```